/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.textilregimara.view.screen;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameInicial = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonLancamentos = new javax.swing.JButton();
        jButtonPessoas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jLabelImageBack = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItemPrincipal = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemPessoas = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuLancamento = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDEM - Sistema de Gerenciamento de Lançamentos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameInicial.setClosable(true);
        jInternalFrameInicial.setTitle("Iniciar");
        jInternalFrameInicial.setToolTipText("");
        jInternalFrameInicial.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/textilregimara/model/image/icon/icone.png"))); // NOI18N
        jInternalFrameInicial.setName(""); // NOI18N
        jInternalFrameInicial.setVisible(true);
        jInternalFrameInicial.getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButtonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/textilregimara/model/image/icon/ico_usuarios.png"))); // NOI18N
        jButtonUsuarios.setToolTipText("Gerencie os usuários");
        jButtonUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonUsuarios.setBorderPainted(false);
        jButtonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUsuarios);
        jButtonUsuarios.setBounds(70, 70, 120, 120);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/textilregimara/model/image/icon/ico_sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonSair.setBorderPainted(false);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair);
        jButtonSair.setBounds(640, 70, 120, 120);

        jButtonLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/textilregimara/model/image/icon/ico_lancamentos.png"))); // NOI18N
        jButtonLancamentos.setToolTipText("Lançamentos");
        jButtonLancamentos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonLancamentos.setBorderPainted(false);
        jButtonLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLancamentosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLancamentos);
        jButtonLancamentos.setBounds(450, 70, 120, 120);

        jButtonPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/textilregimara/model/image/icon/ico_pessoas.png"))); // NOI18N
        jButtonPessoas.setToolTipText("Gerencie os fornecedores");
        jButtonPessoas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonPessoas.setBorderPainted(false);
        jButtonPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPessoasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPessoas);
        jButtonPessoas.setBounds(260, 70, 120, 120);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USUÁRIOS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 200, 120, 16);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SAIR");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(640, 200, 120, 16);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LANÇAMENTOS");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(450, 200, 120, 16);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("FORNECEDORES");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 200, 130, 16);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/textilregimara/model/image/figures/MainBack.png"))); // NOI18N
        jPanel1.add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 830, 280);

        jInternalFrameInicial.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 280);

        getContentPane().add(jInternalFrameInicial);
        jInternalFrameInicial.setBounds(90, 80, 840, 310);

        jLabelImageBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/textilregimara/model/image/figures/MainBack.png"))); // NOI18N
        getContentPane().add(jLabelImageBack);
        jLabelImageBack.setBounds(0, 0, 990, 520);

        jMenuInicio.setText("Inicio");

        jMenuItemPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPrincipal.setText("Principal");
        jMenuItemPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrincipalActionPerformed(evt);
            }
        });
        jMenuInicio.add(jMenuItemPrincipal);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuInicio.add(jMenuItemSair);

        jMenuBar1.add(jMenuInicio);

        jMenuCadastro.setText("Cadastro");

        jMenuItemPessoas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPessoas.setText("Pessoas");
        jMenuItemPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPessoasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemPessoas);

        jMenuItemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemUsuarios.setText("Usuários");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemUsuarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuLancamento.setText("Lançamento");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setText("Lançamentos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuLancamento.add(jMenuItem8);

        jMenuBar1.add(jMenuLancamento);

        jMenuSobre.setText("Sobre");

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSobre.add(jMenuItem1);

        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1007, 582));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(TelaLogin.IMAGE_PATH + "icone.png")));
    }   
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, 
                "IDEM SYSTEM(C)(R) - LANÇAMENTOS\n\n"
              + "MySQL::Java\n"
              + "A.Nicoletti\n "
              + "Contato:(19)98770-0504"
              + "\n\nREV: 1.2 - Dezembro 2018");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPessoasActionPerformed
        // TODO add your handling code here:
        this.abrePessoas();
    }//GEN-LAST:event_jMenuItemPessoasActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.abreLancamentos();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        // TODO add your handling code here:
        this.abreUsuario();
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jButtonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuariosActionPerformed
        // TODO add your handling code here:
        this.abreUsuario();
    }//GEN-LAST:event_jButtonUsuariosActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLancamentosActionPerformed
        // TODO add your handling code here:
        this.abreLancamentos();
    }//GEN-LAST:event_jButtonLancamentosActionPerformed

    private void jButtonPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPessoasActionPerformed
        // TODO add your handling code here:
        this.abrePessoas();
    }//GEN-LAST:event_jButtonPessoasActionPerformed

    private void jMenuItemPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrincipalActionPerformed
        // TODO add your handling code here:
       TelaPrincipal tp = new TelaPrincipal();
       tp.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jMenuItemPrincipalActionPerformed

    public void abreUsuario(){
        TelaUsuarios telaUsuaios = new TelaUsuarios();
        telaUsuaios.setVisible(true);
    }
    
    public void abreLancamentos(){
        TelaLancamentos telaLancamentos = new TelaLancamentos();
        telaLancamentos.setVisible(true);
    }
    
    public void abrePessoas(){
        TelaCadastro telaCadastro = new TelaCadastro();
        telaCadastro.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLancamentos;
    private javax.swing.JButton jButtonPessoas;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JInternalFrame jInternalFrameInicial;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelImageBack;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemPessoas;
    private javax.swing.JMenuItem jMenuItemPrincipal;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuLancamento;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
