/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.textilregimara.view.screen;

import br.com.textilregimara.model.data.DataConnection;
import br.com.textilregimara.model.entities.Login;
import br.com.textilregimara.model.entities.to.DataConnectionTO;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import br.com.textilregimara.model.service.DoaLogin;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.ObjectInputStream;

/**
 *
 * @author Administrador
 */
public class TelaLogin extends javax.swing.JFrame {

    public static String IMAGE_PATH = "/br/com/textilregimara/model/image/icon/";
    private DataConnectionTO dto;
    private DataConnection dataConnection;

    /**
     * Creates new form Login
     */
    public TelaLogin() {
        initComponents();
        getDatabaseName();
        setIcon();
        liberaBotaoEntrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldNomeUsuario = new javax.swing.JTextField();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelSenha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelDadabaseName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAjuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNomeUsuario.setText("Nome do usuário:");

        jPasswordFieldSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelSenha.setText("Senha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNomeUsuario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeUsuario)
                            .addComponent(jLabelSenha))
                        .addGap(0, 161, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 95, 273, 125);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Digite o usuário e senha para ter acesso ao sistema");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 74, 279, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("Seja Bem-Vindo!");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 46, 132, 22);

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar);
        jButtonEntrar.setBounds(120, 230, 75, 28);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(200, 230, 78, 28);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/textilregimara/model/image/icon/IcoDB_null.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(241, 11, 50, 57);

        jLabelDadabaseName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDadabaseName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDadabaseName.setEnabled(false);
        getContentPane().add(jLabelDadabaseName);
        jLabelDadabaseName.setBounds(10, 266, 281, 19);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 248, 0, 0);

        jButtonAjuda.setText("Ajuda");
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAjuda);
        jButtonAjuda.setBounds(14, 229, 70, 28);

        setSize(new java.awt.Dimension(317, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(IMAGE_PATH + "icone.png")));
    }

    private void liberaBotaoEntrar() {
        if (jLabelDadabaseName.getText().equals("NÃO CONFIGURADO")) {
            jButtonEntrar.setEnabled(false);
        }
    }

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        // TODO add your handling code here:
        String nome = jTextFieldNomeUsuario.getText();
        String senha = String.valueOf(jPasswordFieldSenha.getPassword());
        Login l = new Login(nome, senha);
        if (DoaLogin.selectUsuario(l)) {
            TelaPrincipal principal = new TelaPrincipal();
            principal.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao fazer login");
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    public void getDatabaseName() {
        String linha = "";
        try {

            FileInputStream fileInputStram = new FileInputStream("config");
            ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStram);
            dto = (DataConnectionTO) objectInputStream.readObject();
            dataConnection = new DataConnection(dto);

            linha = "S:[" + dataConnection.getPath() + "] DB:[" + dataConnection.getDatabaseName() + "]";
            objectInputStream.close();
            fileInputStram.close();
        } catch (Exception e) {
            linha = "NÃO CONFIGURADO";
        } finally {
            jLabelDadabaseName.setText(linha);
        }
    }

    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        TelaConfiguracaoSql configuracao = new TelaConfiguracaoSql();
        configuracao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDadabaseName;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
